<?php

const LIST_API_TTL = 60;
const STATUS_CODE_SUCCESS = 200;
const STATUS_CODE_FOR_CREATED = 201;
const STATUS_CODE_REDIRECT = 302;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_UNAUTHORIZED = 401;
const STATUS_CODE_FORBIDDEN = 403;
const STATUS_CODE_NOT_FOUND = 404;
const STATUS_CODE_CONFLICT = 409;
const STATUS_CODE_UNPROCESSABLE = 422;
const STATUS_CODE_INTERNAL_ERROR = 500;

